import { Component, OnInit } from '@angular/core';
import { HttpCallsService } from '../http-calls.service';

@Component({
  selector: 'app-main-content',
  templateUrl: './main-content.component.html',
  styleUrls: ['./main-content.component.css']
})
export class MainContentComponent implements OnInit {

master = 'Master';

testdata = [

{
'uniqueBlogName' :  'Just_a_Standard_Format_Post',
'imageSrc' :  '../assets/images/thumbs/masonry/jump-400.jpg',
'postedDate' :  'December 15, 2017',
'title' :  'Just a Standard Format Post.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt eprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Design' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},

{
'uniqueBlogName' :  '',
'imageSrc' :  '',
'postedDate' :  '',
'title' :  '',
'intro' :  'Good design is making something intelligible and memorable. Great design is making something memorable and meaningful.',
'quoteBy' : 'Dieter Rams',
'tags' :  ['Design' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '0',
'comments' : '0',
'postType' : 'quote!',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  '10_Interesting_Facts_About_Caffeine.',
'imageSrc' :  '../assets/images/thumbs/masonry/tulips-400.jpg',
'postedDate' :  'December 15, 2017',
'title' :  '10 Interesting Facts About Caffeine.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/cookies-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'No Sugar Oatmeal Cookies',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health' , 'Cooking'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/wheel-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Visiting Theme Parks Improves Your Health',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health' , 'Lifestyle'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/shutterbug-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Key Benefits Of Family Photography',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Family' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'video!',
'videoLink' : 'https : //player.vimeo.com/video/117310401?color=01aef0&title=0&byline=0&portrait=0',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/guitarman-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'What Your Music Preference Says About You and Your Personality.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Music' , 'Lifestyle'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'audio!',
'videoLink' : '',
'audioLink' : 'media/AirReview-Landmarks-02-ChasingCorporate.mp3',
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '',
'postedDate' :  'December 10, 2017',
'title' :  '',
'intro' :  'The Only Resource You Will Need To Start a Blog Using WordPress.',
'quoteBy' : '',
'tags' :  [],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '',
'comments' : '',
'postType' : 'ad',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{'adLink' : 'https : //colorlib.com'}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/jump-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Create Meaningful Family Moments.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Relationship' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/beetle-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Throwback To The Good Old Days.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/fuji-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Just Another  Standard Format Post',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/sydney-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Planning Your First Trip to Sydney.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Travel'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'Just_a_Standard_Format_Post',
'imageSrc' :  '../assets/images/thumbs/masonry/jump-400.jpg',
'postedDate' :  'December 15, 2017',
'title' :  'Just a Standard Format Post.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt eprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Design' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},

{
'uniqueBlogName' :  '',
'imageSrc' :  '',
'postedDate' :  '',
'title' :  '',
'intro' :  'Good design is making something intelligible and memorable. Great design is making something memorable and meaningful.',
'quoteBy' : 'Dieter Rams',
'tags' :  ['Design' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '0',
'comments' : '0',
'postType' : 'quote!',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  '10_Interesting_Facts_About_Caffeine.',
'imageSrc' :  '../assets/images/thumbs/masonry/tulips-400.jpg',
'postedDate' :  'December 15, 2017',
'title' :  '10 Interesting Facts About Caffeine.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/cookies-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'No Sugar Oatmeal Cookies',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health' , 'Cooking'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/wheel-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Visiting Theme Parks Improves Your Health',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health' , 'Lifestyle'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/shutterbug-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Key Benefits Of Family Photography',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Family' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'video!',
'videoLink' : 'https : //player.vimeo.com/video/117310401?color=01aef0&title=0&byline=0&portrait=0',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/guitarman-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'What Your Music Preference Says About You and Your Personality.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Music' , 'Lifestyle'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'audio!',
'videoLink' : '',
'audioLink' : 'media/AirReview-Landmarks-02-ChasingCorporate.mp3',
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '',
'postedDate' :  'December 10, 2017',
'title' :  '',
'intro' :  'The Only Resource You Will Need To Start a Blog Using WordPress.',
'quoteBy' : '',
'tags' :  [],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '',
'comments' : '',
'postType' : 'ad',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{'adLink' : 'https : //colorlib.com'}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/jump-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Create Meaningful Family Moments.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Relationship' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/beetle-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Throwback To The Good Old Days.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/fuji-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Just Another  Standard Format Post',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/sydney-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Planning Your First Trip to Sydney.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Travel'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'Just_a_Standard_Format_Post',
'imageSrc' :  '../assets/images/thumbs/masonry/jump-400.jpg',
'postedDate' :  'December 15, 2017',
'title' :  'Just a Standard Format Post.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt eprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Design' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},

{
'uniqueBlogName' :  '',
'imageSrc' :  '',
'postedDate' :  '',
'title' :  '',
'intro' :  'Good design is making something intelligible and memorable. Great design is making something memorable and meaningful.',
'quoteBy' : 'Dieter Rams',
'tags' :  ['Design' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '0',
'comments' : '0',
'postType' : 'quote!',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  '10_Interesting_Facts_About_Caffeine.',
'imageSrc' :  '../assets/images/thumbs/masonry/tulips-400.jpg',
'postedDate' :  'December 15, 2017',
'title' :  '10 Interesting Facts About Caffeine.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/cookies-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'No Sugar Oatmeal Cookies',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health' , 'Cooking'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/wheel-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Visiting Theme Parks Improves Your Health',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Health' , 'Lifestyle'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/shutterbug-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Key Benefits Of Family Photography',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Family' , 'Photography'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'video!',
'videoLink' : 'https : //player.vimeo.com/video/117310401?color=01aef0&title=0&byline=0&portrait=0',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/guitarman-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'What Your Music Preference Says About You and Your Personality.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Music' , 'Lifestyle'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'audio!',
'videoLink' : '',
'audioLink' : 'media/AirReview-Landmarks-02-ChasingCorporate.mp3',
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '',
'postedDate' :  'December 10, 2017',
'title' :  '',
'intro' :  'The Only Resource You Will Need To Start a Blog Using WordPress.',
'quoteBy' : '',
'tags' :  [],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '',
'comments' : '',
'postType' : 'ad',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{'adLink' : 'https : //colorlib.com'}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/jump-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Create Meaningful Family Moments.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Relationship' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/beetle-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Throwback To The Good Old Days.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/fuji-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Just Another  Standard Format Post',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Family'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
},
{
'uniqueBlogName' :  'No_Sugar_Oatmeal_Cookies.',
'imageSrc' :  '../assets/images/thumbs/masonry/sydney-400.jpg',
'postedDate' :  'December 10, 2017',
'title' :  'Planning Your First Trip to Sydney.',
'intro' :  'Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua...',
'quoteBy' : '',
'tags' :  ['Lifestyle' , 'Travel'],
'mostFeaturedPost' : 'false',
'featuredPost' : 'false',
'likes' : '40',
'comments' : '10',
'postType' : 'text',
'videoLink' : '',
'audioLink' : '',
'otherLinks' : [{}],
'allImages' : []
}

];
 allpost = [];
  constructor(private http: HttpCallsService) { }

  ngOnInit() {
        this.http.getAllPosts().subscribe(data  => {
      console.log(data);
      this.allpost.push(data);
      //this.testdata.push(...this.allpost[0]);

      this.testdata = [...this.allpost[0], ...this.testdata];

     // alert(this.testdata.length);
    }, error => {
      alert(error);
  });

}
}
